-- SNS 로그인(Google/Kakao) 키를 Admin 연동 설정에서 관리
INSERT INTO integration_configs (key, value_ciphertext, is_secret) VALUES
    ('GOOGLE_OAUTH_CLIENT_ID', NULL, FALSE),
    ('GOOGLE_OAUTH_CLIENT_SECRET', NULL, TRUE),
    ('GOOGLE_OAUTH_REDIRECT_URI', NULL, FALSE),
    ('KAKAO_OAUTH_CLIENT_ID', NULL, FALSE),
    ('KAKAO_OAUTH_CLIENT_SECRET', NULL, TRUE),
    ('KAKAO_OAUTH_REDIRECT_URI', NULL, FALSE),
    ('KAKAO_OAUTH_ENABLED', NULL, FALSE)
ON CONFLICT (key) DO NOTHING;
